### ISSUE TITLE
Speed up calculations for large areas

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/efficiency-explorer#4]
The efficiency explorer tool can refresh slowly for large suppliers.  It would be good to improve the computational speed.  

H/T Gordon Ng

**Comment by dmarulli** [comment]
So one avenue here could be to send the relevant data over to the client on the initial page load, and make the queries for different scenarios client-side. The motivation would be to reduce the amount of functionality that relies on network communication. I'm not sure how well-suited cartodb.js is for this, but it's worth exploring.

**Comment by christophertull** [comment]
Copied to residential EE https://github.com/California-Data-Collaborative/residential-efficiency-explorer/issues/1
