### ISSUE TITLE
Use proper number of days in each month

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/efficiency-explorer#5]
Don't assume a default 30.4. Edit supplier_report table?

**Comment by patwater** [comment]
Yeah this will be key.

**Comment by christophertull** [comment]
This is done, right? Can close if so

**Comment by dmarulli** [comment]
Yes, we can close this one because it does done at the state level. But as a note (as of this comment's timestamp) NEE still uses average.
